Console.WriteLine("Please maximize this window and enter a line of six letter words you wish to make big.");
string input = Console.ReadLine().ToUpper();

string[] seperateWords = input.Split(' ');
List<string> words = seperateWords.ToList();
foreach (string word in words)
{
    WriteBig(word);
    Console.Write("\n");
}

static void WriteBig(string word)
{
    var bigLetters = new Dictionary<char, Dictionary<int, string>>();
    bigLetters.Add('A', new Dictionary<int, string>()
    {
        {1, "   AAAAAAAAAAAAAAAAAAAAAAA    " },
        {2, "  AAAAAAAAAAAAAAAAAAAAAAAAA   " },
        {3, " AAAAAAAAAAAAAAAAAAAAAAAAAAA  " },
        {4, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAA " },
        {5, "AAAAAAAAA            AAAAAAAAA" },
        {6, "AAAAAAAAA            AAAAAAAAA" },
        {7, "AAAAAAAAA            AAAAAAAAA" },
        {8, "AAAAAAAAA            AAAAAAAAA" },
        {9, "AAAAAAAAA            AAAAAAAAA" },
        {10,"AAAAAAAAA            AAAAAAAAA" },
        {11,"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
        {12,"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
        {13,"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
        {14,"AAAAAAAAA            AAAAAAAAA" },
        {15,"AAAAAAAAA            AAAAAAAAA" },
        {16,"AAAAAAAAA            AAAAAAAAA" },
        {17,"AAAAAAAAA            AAAAAAAAA" },
        {18,"AAAAAAAAA            AAAAAAAAA" },
        {19,"AAAAAAAAA            AAAAAAAAA" },
        {20,"AAAAAAAAA            AAAAAAAAA" },
        {21,"AAAAAAAAA            AAAAAAAAA" },
        {22,"AAAAAAAAA            AAAAAAAAA" },
        {23,"AAAAAAAAA            AAAAAAAAA" }
    });
    bigLetters.Add('B', new Dictionary<int, string>()
    {
        {1, "BBBBBBBBBBBBBBBBBBBBBBBBBB    " },
        {2, "BBBBBBBBBBBBBBBBBBBBBBBBBBB   " },
        {3, "BBBBBBBBBBBBBBBBBBBBBBBBBBBB  " },
        {4, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB " },
        {5, "BBBBBBBBB            BBBBBBBBB" },
        {6, "BBBBBBBBB             BBBBBBBB" },
        {7, "BBBBBBBBB              BBBBBBB" },
        {8, "BBBBBBBBB              BBBBBBB" },
        {9, "BBBBBBBBB             BBBBBBBB" },
        {10,"BBBBBBBBB            BBBBBBBBB" },
        {11,"BBBBBBBBBBBBBBBBBBBBBBBBBBBBB " },
        {12,"BBBBBBBBBBBBBBBBBBBBBBBBBBBB  " },
        {13,"BBBBBBBBBBBBBBBBBBBBBBBBBBBBB " },
        {14,"BBBBBBBBB            BBBBBBBBB" },
        {15,"BBBBBBBBB             BBBBBBBB" },
        {16,"BBBBBBBBB              BBBBBBB" },
        {17,"BBBBBBBBB              BBBBBBB" },
        {18,"BBBBBBBBB             BBBBBBBB" },
        {19,"BBBBBBBBB            BBBBBBBBB" },
        {20,"BBBBBBBBBBBBBBBBBBBBBBBBBBBBB " },
        {21,"BBBBBBBBBBBBBBBBBBBBBBBBBBBB  " },
        {22,"BBBBBBBBBBBBBBBBBBBBBBBBBBB   " },
        {23,"BBBBBBBBBBBBBBBBBBBBBBBBBB    " }
    });
    bigLetters.Add('C', new Dictionary<int, string>()
    {
        {1, "    CCCCCCCCCCCCCCCCCCCCCC    " },
        {2, "   CCCCCCCCCCCCCCCCCCCCCCCC   " },
        {3, "  CCCCCCCCCCCCCCCCCCCCCCCCCC  " },
        {4, " CCCCCCCCCCCCCCCCCCCCCCCCCCCC " },
        {5, "CCCCCCCCC            CCCCCCCCC" },
        {6, "CCCCCCCCC             CCCCCCCC" },
        {7, "CCCCCCCCC              CCCCCCC" },
        {8, "CCCCCCCCC               CCCCCC" },
        {9, "CCCCCCCCC                     " },
        {10,"CCCCCCCCC                     " },
        {11,"CCCCCCCCC                     " },
        {12,"CCCCCCCCC                     " },
        {13,"CCCCCCCCC                     " },
        {14,"CCCCCCCCC                     " },
        {15,"CCCCCCCCC                     " },
        {16,"CCCCCCCCC               CCCCCC" },
        {17,"CCCCCCCCC              CCCCCCC" },
        {18,"CCCCCCCCC             CCCCCCCC" },
        {19,"CCCCCCCCC            CCCCCCCCC" },
        {20," CCCCCCCCCCCCCCCCCCCCCCCCCCCC " },
        {21,"  CCCCCCCCCCCCCCCCCCCCCCCCCC  " },
        {22,"   CCCCCCCCCCCCCCCCCCCCCCCC   " },
        {23,"    CCCCCCCCCCCCCCCCCCCCCC    " }
    });
    bigLetters.Add('D', new Dictionary<int, string>()
    {
        {1, "DDDDDDDDDDDDDDDDDDDDDDDDDD    " },
        {2, "DDDDDDDDDDDDDDDDDDDDDDDDDDD   " },
        {3, "DDDDDDDDDDDDDDDDDDDDDDDDDDDD  " },
        {4, "DDDDDDDDDDDDDDDDDDDDDDDDDDDDD " },
        {5, "DDDDDDDDD        DDDDDDDDDDDDD" },
        {6, "DDDDDDDDD         DDDDDDDDDDDD" },
        {7, "DDDDDDDDD          DDDDDDDDDDD" },
        {8, "DDDDDDDDD           DDDDDDDDDD" },
        {9, "DDDDDDDDD            DDDDDDDDD" },
        {10,"DDDDDDDDD             DDDDDDDD" },
        {11,"DDDDDDDDD              DDDDDDD" },
        {12,"DDDDDDDDD               DDDDDD" },
        {13,"DDDDDDDDD              DDDDDDD" },
        {14,"DDDDDDDDD             DDDDDDDD" },
        {15,"DDDDDDDDD            DDDDDDDDD" },
        {16,"DDDDDDDDD           DDDDDDDDDD" },
        {17,"DDDDDDDDD          DDDDDDDDDDD" },
        {18,"DDDDDDDDD         DDDDDDDDDDDD" },
        {19,"DDDDDDDDD        DDDDDDDDDDDDD" },
        {20,"DDDDDDDDDDDDDDDDDDDDDDDDDDDDD " },
        {21,"DDDDDDDDDDDDDDDDDDDDDDDDDDDD  " },
        {22,"DDDDDDDDDDDDDDDDDDDDDDDDDDD   " },
        {23,"DDDDDDDDDDDDDDDDDDDDDDDDDD    " }
    });
    bigLetters.Add('E', new Dictionary<int, string>()
    {
        {1, "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" },
        {2, "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" },
        {3, "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" },
        {4, "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" },
        {5, "EEEEEEEEE                     " },
        {6, "EEEEEEEEE                     " },
        {7, "EEEEEEEEE                     " },
        {8, "EEEEEEEEE                     " },
        {9, "EEEEEEEEE                     " },
        {10,"EEEEEEEEE                     " },
        {11,"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" },
        {12,"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" },
        {13,"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" },
        {14,"EEEEEEEEE                     " },
        {15,"EEEEEEEEE                     " },
        {16,"EEEEEEEEE                     " },
        {17,"EEEEEEEEE                     " },
        {18,"EEEEEEEEE                     " },
        {19,"EEEEEEEEE                     " },
        {20,"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" },
        {21,"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" },
        {22,"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" },
        {23,"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" }
    });
    bigLetters.Add('F', new Dictionary<int, string>()
    {
        {1, "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" },
        {2, "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" },
        {3, "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" },
        {4, "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" },
        {5, "FFFFFFFFF                     " },
        {6, "FFFFFFFFF                     " },
        {7, "FFFFFFFFF                     " },
        {8, "FFFFFFFFF                     " },
        {9, "FFFFFFFFF                     " },
        {10,"FFFFFFFFF                     " },
        {11,"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" },
        {12,"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" },
        {13,"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" },
        {14,"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" },
        {15,"FFFFFFFFF                     " },
        {16,"FFFFFFFFF                     " },
        {17,"FFFFFFFFF                     " },
        {18,"FFFFFFFFF                     " },
        {19,"FFFFFFFFF                     " },
        {20,"FFFFFFFFF                     " },
        {21,"FFFFFFFFF                     " },
        {22,"FFFFFFFFF                     " },
        {23,"FFFFFFFFF                     " }
    });
    bigLetters.Add('G', new Dictionary<int, string>()
    {
        {1, "    GGGGGGGGGGGGGGGGGGGGGG    " },
        {2, "   GGGGGGGGGGGGGGGGGGGGGGGG   " },
        {3, "  GGGGGGGGGGGGGGGGGGGGGGGGGG  " },
        {4, " GGGGGGGGGGGGGGGGGGGGGGGGGGGG " },
        {5, "GGGGGGGGG            GGGGGGGGG" },
        {6, "GGGGGGGGG             GGGGGGGG" },
        {7, "GGGGGGGGG              GGGGGGG" },
        {8, "GGGGGGGGG                     " },
        {9, "GGGGGGGGG                     " },
        {10,"GGGGGGGGG                     " },
        {11,"GGGGGGGGG                     " },
        {12,"GGGGGGGGG                     " },
        {13,"GGGGGGGGG                     " },
        {14,"GGGGGGGGG      GGGGGGGGGGGGGGG" },
        {15,"GGGGGGGGG      GGGGGGGGGGGGGGG" },
        {16,"GGGGGGGGG      GGGGGGGGGGGGGGG" },
        {17,"GGGGGGGGG              GGGGGGG" },
        {18,"GGGGGGGGG             GGGGGGGG" },
        {19,"GGGGGGGGG            GGGGGGGGG" },
        {20," GGGGGGGGGGGGGGGGGGGGGGGGGGGG " },
        {21,"  GGGGGGGGGGGGGGGGGGGGGGGGGG  " },
        {22,"   GGGGGGGGGGGGGGGGGGGGGGGG   " },
        {23,"    GGGGGGGGGGGGGGGGGGGGGG    " }
    });
    bigLetters.Add('H', new Dictionary<int, string>()
    {
        {1, "HHHHHHHHH            HHHHHHHHH" },
        {2, "HHHHHHHHH            HHHHHHHHH" },
        {3, "HHHHHHHHH            HHHHHHHHH" },
        {4, "HHHHHHHHH            HHHHHHHHH" },
        {5, "HHHHHHHHH            HHHHHHHHH" },
        {6, "HHHHHHHHH            HHHHHHHHH" },
        {7, "HHHHHHHHH            HHHHHHHHH" },
        {8, "HHHHHHHHH            HHHHHHHHH" },
        {9, "HHHHHHHHH            HHHHHHHHH" },
        {10,"HHHHHHHHH            HHHHHHHHH" },
        {11,"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH" },
        {12,"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH" },
        {13,"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH" },
        {14,"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH" },
        {15,"HHHHHHHHH            HHHHHHHHH" },
        {16,"HHHHHHHHH            HHHHHHHHH" },
        {17,"HHHHHHHHH            HHHHHHHHH" },
        {18,"HHHHHHHHH            HHHHHHHHH" },
        {19,"HHHHHHHHH            HHHHHHHHH" },
        {20,"HHHHHHHHH            HHHHHHHHH" },
        {21,"HHHHHHHHH            HHHHHHHHH" },
        {22,"HHHHHHHHH            HHHHHHHHH" },
        {23,"HHHHHHHHH            HHHHHHHHH" }
    });
    bigLetters.Add('I', new Dictionary<int, string>()
    {
        {1, "IIIIIIIIIIIIIIIIIIIIIIIIIIIIII" },
        {2, "IIIIIIIIIIIIIIIIIIIIIIIIIIIIII" },
        {3, "IIIIIIIIIIIIIIIIIIIIIIIIIIIIII" },
        {4, "IIIIIIIIIIIIIIIIIIIIIIIIIIIIII" },
        {5, "          IIIIIIIIII          " },
        {6, "          IIIIIIIIII          " },
        {7, "          IIIIIIIIII          " },
        {8, "          IIIIIIIIII          " },
        {9, "          IIIIIIIIII          " },
        {10,"          IIIIIIIIII          " },
        {11,"          IIIIIIIIII          " },
        {12,"          IIIIIIIIII          " },
        {13,"          IIIIIIIIII          " },
        {14,"          IIIIIIIIII          " },
        {15,"          IIIIIIIIII          " },
        {16,"          IIIIIIIIII          " },
        {17,"          IIIIIIIIII          " },
        {18,"          IIIIIIIIII          " },
        {19,"          IIIIIIIIII          " },
        {20,"IIIIIIIIIIIIIIIIIIIIIIIIIIIIII" },
        {21,"IIIIIIIIIIIIIIIIIIIIIIIIIIIIII" },
        {22,"IIIIIIIIIIIIIIIIIIIIIIIIIIIIII" },
        {23,"IIIIIIIIIIIIIIIIIIIIIIIIIIIIII" }
    });
    bigLetters.Add('J', new Dictionary<int, string>()
    {
        {1, "   JJJJJJJJJJJJJJJJJJJJJJJJJJJ" },
        {2, "   JJJJJJJJJJJJJJJJJJJJJJJJJJJ" },
        {3, "   JJJJJJJJJJJJJJJJJJJJJJJJJJJ" },
        {4, "   JJJJJJJJJJJJJJJJJJJJJJJJJJJ" },
        {5, "                    JJJJJJJJJJ" },
        {6, "                    JJJJJJJJJJ" },
        {7, "                    JJJJJJJJJJ" },
        {8, "                    JJJJJJJJJJ" },
        {9, "                    JJJJJJJJJJ" },
        {10,"                    JJJJJJJJJJ" },
        {11,"                    JJJJJJJJJJ" },
        {12,"                    JJJJJJJJJJ" },
        {13,"                    JJJJJJJJJJ" },
        {14,"                    JJJJJJJJJJ" },
        {15,"JJJJJJJJJ           JJJJJJJJJJ" },
        {16,"JJJJJJJJJ           JJJJJJJJJJ" },
        {17,"JJJJJJJJJ           JJJJJJJJJJ" },
        {18,"JJJJJJJJJ           JJJJJJJJJJ" },
        {19,"JJJJJJJJJJ         JJJJJJJJJJJ" },
        {20,"JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ" },
        {21," JJJJJJJJJJJJJJJJJJJJJJJJJJJJ " },
        {22,"  JJJJJJJJJJJJJJJJJJJJJJJJJJ  " },
        {23,"   JJJJJJJJJJJJJJJJJJJJJJJJ   " }
    });
    bigLetters.Add('K', new Dictionary<int, string>()
    {
        {1, "KKKKKKKKK           KKKKKKKKKK" },
        {2, "KKKKKKKKK          KKKKKKKKKK " },
        {3, "KKKKKKKKK         KKKKKKKKKK  " },
        {4, "KKKKKKKKK        KKKKKKKKKK   " },
        {5, "KKKKKKKKK       KKKKKKKKKK    " },
        {6, "KKKKKKKKK      KKKKKKKKKK     " },
        {7, "KKKKKKKKK     KKKKKKKKKK      " },
        {8, "KKKKKKKKK    KKKKKKKKKK       " },
        {9, "KKKKKKKKK   KKKKKKKKKK        " },
        {10,"KKKKKKKKK  KKKKKKKKKK         " },
        {11,"KKKKKKKKKKKKKKKKKKKK          " },
        {12,"KKKKKKKKKKKKKKKKKKK           " },
        {13,"KKKKKKKKKKKKKKKKKKKK          " },
        {14,"KKKKKKKKKKKKKKKKKKKKK         " },
        {15,"KKKKKKKKK   KKKKKKKKKK        " },
        {16,"KKKKKKKKK    KKKKKKKKKK       " },
        {17,"KKKKKKKKK     KKKKKKKKKK      " },
        {18,"KKKKKKKKK      KKKKKKKKKK     " },
        {19,"KKKKKKKKK       KKKKKKKKKK    " },
        {20,"KKKKKKKKK        KKKKKKKKKK   " },
        {21,"KKKKKKKKK         KKKKKKKKKK  " },
        {22,"KKKKKKKKK          KKKKKKKKKK " },
        {23,"KKKKKKKKK           KKKKKKKKKK" }
    });
    bigLetters.Add('L', new Dictionary<int, string>()
    {
        {1, "LLLLLLLLL                     " },
        {2, "LLLLLLLLL                     " },
        {3, "LLLLLLLLL                     " },
        {4, "LLLLLLLLL                     " },
        {5, "LLLLLLLLL                     " },
        {6, "LLLLLLLLL                     " },
        {7, "LLLLLLLLL                     " },
        {8, "LLLLLLLLL                     " },
        {9, "LLLLLLLLL                     " },
        {10,"LLLLLLLLL                     " },
        {11,"LLLLLLLLL                     " },
        {12,"LLLLLLLLL                     " },
        {13,"LLLLLLLLL                     " },
        {14,"LLLLLLLLL                     " },
        {15,"LLLLLLLLL                     " },
        {16,"LLLLLLLLL                     " },
        {17,"LLLLLLLLL                     " },
        {18,"LLLLLLLLL                     " },
        {19,"LLLLLLLLL                     " },
        {20,"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLL" },
        {21,"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLL" },
        {22,"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLL" },
        {23,"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLL" }
    });
    bigLetters.Add('M', new Dictionary<int, string>()
    {
        {1, "MMMMMMMMMMM        MMMMMMMMMMM" },
        {2, "MMMMMMMMMMM        MMMMMMMMMMM" },
        {3, "MMMMMMMMMMM        MMMMMMMMMMM" },
        {4, "MMMMMMMMMMM        MMMMMMMMMMM" },
        {5, "MMMMMM MMMMM      MMMMM MMMMMM" },
        {6, "MMMMMM MMMMM      MMMMM MMMMMM" },
        {7, "MMMMMM MMMMM      MMMMM MMMMMM" },
        {8, "MMMMMM MMMMM      MMMMM MMMMMM" },
        {9, "MMMMMM  MMMMM    MMMMM  MMMMMM" },
        {10,"MMMMMM  MMMMM    MMMMM  MMMMMM" },
        {11,"MMMMMM  MMMMM    MMMMM  MMMMMM" },
        {12,"MMMMMM  MMMMM    MMMMM  MMMMMM" },
        {13,"MMMMMM   MMMMM  MMMMM   MMMMMM" },
        {14,"MMMMMM   MMMMM  MMMMM   MMMMMM" },
        {15,"MMMMMM   MMMMM  MMMMM   MMMMMM" },
        {16,"MMMMMM   MMMMM  MMMMM   MMMMMM" },
        {17,"MMMMMM    MMMMMMMMMM    MMMMMM" },
        {18,"MMMMMM    MMMMMMMMMM    MMMMMM" },
        {19,"MMMMMM    MMMMMMMMMM    MMMMMM" },
        {20,"MMMMMM    MMMMMMMMMM    MMMMMM" },
        {21,"MMMMMM                  MMMMMM" },
        {22,"MMMMMM                  MMMMMM" },
        {23,"MMMMMM                  MMMMMM" }
    });
    bigLetters.Add('N', new Dictionary<int, string>()
    {
        {1, "NNNNNNNNN               NNNNNN" },
        {2, "NNNNNNNNN               NNNNNN" },
        {3, "NNNNNNNNN               NNNNNN" },
        {4, "NNNNNNNNN               NNNNNN" },
        {5, "NNNNNN NNNN             NNNNNN" },
        {6, "NNNNNN NNNNN            NNNNNN" },
        {7, "NNNNNN  NNNN            NNNNNN" },
        {8, "NNNNNN    NNNN          NNNNNN" },
        {9, "NNNNNN    NNNNN         NNNNNN" },
        {10,"NNNNNN     NNNN         NNNNNN" },
        {11,"NNNNNN       NNNN       NNNNNN" },
        {12,"NNNNNN       NNNNN      NNNNNN" },
        {13,"NNNNNN        NNNN      NNNNNN" },
        {14,"NNNNNN          NNNN    NNNNNN" },
        {15,"NNNNNN          NNNNN   NNNNNN" },
        {16,"NNNNNN           NNNN   NNNNNN" },
        {17,"NNNNNN            NNNN  NNNNNN" },
        {18,"NNNNNN            NNNNN NNNNNN" },
        {19,"NNNNNN             NNNN NNNNNN" },
        {20,"NNNNNN               NNNNNNNNN" },
        {21,"NNNNNN               NNNNNNNNN" },
        {22,"NNNNNN               NNNNNNNNN" },
        {23,"NNNNNN               NNNNNNNNN" }
    });
    bigLetters.Add('O', new Dictionary<int, string>()
    {
        {1, "    OOOOOOOOOOOOOOOOOOOOOO    " },
        {2, "   OOOOOOOOOOOOOOOOOOOOOOOO   " },
        {3, "  OOOOOOOOOOOOOOOOOOOOOOOOOO  " },
        {4, " OOOOOOOOOOOOOOOOOOOOOOOOOOOO " },
        {5, "OOOOOOOOO            OOOOOOOOO" },
        {6, "OOOOOOOOO            OOOOOOOOO" },
        {7, "OOOOOOOOO            OOOOOOOOO" },
        {8, "OOOOOOOOO            OOOOOOOOO" },
        {9, "OOOOOOOOO            OOOOOOOOO" },
        {10,"OOOOOOOOO            OOOOOOOOO" },
        {11,"OOOOOOOOO            OOOOOOOOO" },
        {12,"OOOOOOOOO            OOOOOOOOO" },
        {13,"OOOOOOOOO            OOOOOOOOO" },
        {14,"OOOOOOOOO            OOOOOOOOO" },
        {15,"OOOOOOOOO            OOOOOOOOO" },
        {16,"OOOOOOOOO            OOOOOOOOO" },
        {17,"OOOOOOOOO            OOOOOOOOO" },
        {18,"OOOOOOOOO            OOOOOOOOO" },
        {19,"OOOOOOOOO            OOOOOOOOO" },
        {20," OOOOOOOOOOOOOOOOOOOOOOOOOOOO " },
        {21,"  OOOOOOOOOOOOOOOOOOOOOOOOOO  " },
        {22,"   OOOOOOOOOOOOOOOOOOOOOOOO   " },
        {23,"    OOOOOOOOOOOOOOOOOOOOOO    " }
    });
    bigLetters.Add('P', new Dictionary<int, string>()
    {
        {1, "PPPPPPPPPPPPPPPPPPPPPPPPPPP   " },
        {2, "PPPPPPPPPPPPPPPPPPPPPPPPPPPP  " },
        {3, "PPPPPPPPPPPPPPPPPPPPPPPPPPPPP " },
        {4, "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP" },
        {5, "PPPPPPPPP            PPPPPPPPP" },
        {6, "PPPPPPPPP            PPPPPPPPP" },
        {7, "PPPPPPPPP            PPPPPPPPP" },
        {8, "PPPPPPPPP            PPPPPPPPP" },
        {9, "PPPPPPPPP            PPPPPPPPP" },
        {10,"PPPPPPPPP            PPPPPPPPP" },
        {11,"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP" },
        {12,"PPPPPPPPPPPPPPPPPPPPPPPPPPPPP " },
        {13,"PPPPPPPPPPPPPPPPPPPPPPPPPPPP  " },
        {14,"PPPPPPPPPPPPPPPPPPPPPPPPPPP   " },
        {15,"PPPPPPPPP                     " },
        {16,"PPPPPPPPP                     " },
        {17,"PPPPPPPPP                     " },
        {18,"PPPPPPPPP                     " },
        {19,"PPPPPPPPP                     " },
        {20,"PPPPPPPPP                     " },
        {21,"PPPPPPPPP                     " },
        {22,"PPPPPPPPP                     " },
        {23,"PPPPPPPPP                     " }
    });
    bigLetters.Add('Q', new Dictionary<int, string>()
    {
        {1, "    QQQQQQQQQQQQQQQQQQ        " },
        {2, "   QQQQQQQQQQQQQQQQQQQQ       " },
        {3, "  QQQQQQQQQQQQQQQQQQQQQQ      " },
        {4, " QQQQQQQQQQQQQQQQQQQQQQQQ     " },
        {5, "QQQQQQQ            QQQQQQQ    " },
        {6, "QQQQQQQ            QQQQQQQ    " },
        {7, "QQQQQQQ            QQQQQQQ    " },
        {8, "QQQQQQQ            QQQQQQQ    " },
        {9, "QQQQQQQ            QQQQQQQ    " },
        {10,"QQQQQQQ            QQQQQQQ    " },
        {11,"QQQQQQQ            QQQQQQQ    " },
        {12,"QQQQQQQ            QQQQQQQ    " },
        {13,"QQQQQQQ            QQQQQQQ    " },
        {14,"QQQQQQQ            QQQQQQQ    " },
        {15,"QQQQQQQ            QQQQQQQ    " },
        {16,"QQQQQQQ     QQQQQ  QQQQQQQ    " },
        {17,"QQQQQQQ      QQQQQ QQQQQQQ    " },
        {18,"QQQQQQQ       QQQQQQQQQQQQ    " },
        {19,"QQQQQQQ        QQQQQQQQQQQ    " },
        {20," QQQQQQQQQQQQQQQQQQQQQQQQ     " },
        {21,"  QQQQQQQQQQQQQQQQQQQQQQQQQQ  " },
        {22,"   QQQQQQQQQQQQQQQQQQQQ QQQQQ " },
        {23,"    QQQQQQQQQQQQQQQQQQ   QQQQQ" }
    });
    bigLetters.Add('R', new Dictionary<int, string>()
    {
        {1, "RRRRRRRRRRRRRRRRRRRRRRRRRR    " },
        {2, "RRRRRRRRRRRRRRRRRRRRRRRRRRR   " },
        {3, "RRRRRRRRRRRRRRRRRRRRRRRRRRRR  " },
        {4, "RRRRRRRRRRRRRRRRRRRRRRRRRRRRR " },
        {5, "RRRRRRRRRR          RRRRRRRRRR" },
        {6, "RRRRRRRRR            RRRRRRRRR" },
        {7, "RRRRRRRRR            RRRRRRRRR" },
        {8, "RRRRRRRRR            RRRRRRRRR" },
        {9, "RRRRRRRRR            RRRRRRRRR" },
        {10,"RRRRRRRRRR          RRRRRRRRRR" },
        {11,"RRRRRRRRRRRRRRRRRRRRRRRRRRRRR " },
        {12,"RRRRRRRRRRRRRRRRRRRRRRRRRRRR  " },
        {13,"RRRRRRRRRRRRRRRRRRRRRRRRRRRRR " },
        {14,"RRRRRRRRR            RRRRRRRRR" },
        {15,"RRRRRRRRR            RRRRRRRRR" },
        {16,"RRRRRRRRR            RRRRRRRRR" },
        {17,"RRRRRRRRR            RRRRRRRRR" },
        {18,"RRRRRRRRR            RRRRRRRRR" },
        {19,"RRRRRRRRR            RRRRRRRRR" },
        {20,"RRRRRRRRR            RRRRRRRRR" },
        {21,"RRRRRRRRR            RRRRRRRRR" },
        {22,"RRRRRRRRR            RRRRRRRRR" },
        {23,"RRRRRRRRR            RRRRRRRRR" }
    });
    bigLetters.Add('S', new Dictionary<int, string>()
{
        {1, "    SSSSSSSSSSSSSSSSSSSSSS    " },
        {2, "   SSSSSSSSSSSSSSSSSSSSSSSS   " },
        {3, "  SSSSSSSSSSSSSSSSSSSSSSSSSS  " },
        {4, " SSSSSSSSSSSSSSSSSSSSSSSSSSSS " },
        {5, "SSSSSSSSS            SSSSSSSSS" },
        {6, "SSSSSSSSS             SSSSSSSS" },
        {7, "SSSSSSSSS              SSSSSSS" },
        {8, "SSSSSSSSS                     " },
        {9, "SSSSSSSSS                     " },
        {10,"SSSSSSSSS                     " },
        {11,"SSSSSSSSSSSSSSSSSSSSSSSSSSSS  " },
        {12," SSSSSSSSSSSSSSSSSSSSSSSSSSSS " },
        {13,"  SSSSSSSSSSSSSSSSSSSSSSSSSSSS" },
        {14,"                     SSSSSSSSS" },
        {15,"                     SSSSSSSSS" },
        {16,"                     SSSSSSSSS" },
        {17,"SSSSSSS              SSSSSSSSS" },
        {18,"SSSSSSSS             SSSSSSSSS" },
        {19,"SSSSSSSSS            SSSSSSSSS" },
        {20," SSSSSSSSSSSSSSSSSSSSSSSSSSSS " },
        {21,"  SSSSSSSSSSSSSSSSSSSSSSSSSS  " },
        {22,"   SSSSSSSSSSSSSSSSSSSSSSSS   " },
        {23,"    SSSSSSSSSSSSSSSSSSSSSS    " }
    });
    bigLetters.Add('T', new Dictionary<int, string>()
    {
        {1, "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" },
        {2, "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" },
        {3, "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" },
        {4, "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" },
        {5, "          TTTTTTTTTT          " },
        {6, "          TTTTTTTTTT          " },
        {7, "          TTTTTTTTTT          " },
        {8, "          TTTTTTTTTT          " },
        {9, "          TTTTTTTTTT          " },
        {10,"          TTTTTTTTTT          " },
        {11,"          TTTTTTTTTT          " },
        {12,"          TTTTTTTTTT          " },
        {13,"          TTTTTTTTTT          " },
        {14,"          TTTTTTTTTT          " },
        {15,"          TTTTTTTTTT          " },
        {16,"          TTTTTTTTTT          " },
        {17,"          TTTTTTTTTT          " },
        {18,"          TTTTTTTTTT          " },
        {19,"          TTTTTTTTTT          " },
        {20,"          TTTTTTTTTT          " },
        {21,"          TTTTTTTTTT          " },
        {22,"          TTTTTTTTTT          " },
        {23,"          TTTTTTTTTT          " }
    });
    bigLetters.Add('U', new Dictionary<int, string>()
    {
        {1, "UUUUUUUUU            UUUUUUUUU" },
        {2, "UUUUUUUUU            UUUUUUUUU" },
        {3, "UUUUUUUUU            UUUUUUUUU" },
        {4, "UUUUUUUUU            UUUUUUUUU" },
        {5, "UUUUUUUUU            UUUUUUUUU" },
        {6, "UUUUUUUUU            UUUUUUUUU" },
        {7, "UUUUUUUUU            UUUUUUUUU" },
        {8, "UUUUUUUUU            UUUUUUUUU" },
        {9, "UUUUUUUUU            UUUUUUUUU" },
        {10,"UUUUUUUUU            UUUUUUUUU" },
        {11,"UUUUUUUUU            UUUUUUUUU" },
        {12,"UUUUUUUUU            UUUUUUUUU" },
        {13,"UUUUUUUUU            UUUUUUUUU" },
        {14,"UUUUUUUUU            UUUUUUUUU" },
        {15,"UUUUUUUUU            UUUUUUUUU" },
        {16,"UUUUUUUUU            UUUUUUUUU" },
        {17,"UUUUUUUUU            UUUUUUUUU" },
        {18,"UUUUUUUUUU          UUUUUUUUUU" },
        {19,"UUUUUUUUUUU        UUUUUUUUUUU" },
        {20," UUUUUUUUUUUUUUUUUUUUUUUUUUUU " },
        {21,"  UUUUUUUUUUUUUUUUUUUUUUUUUU  " },
        {22,"   UUUUUUUUUUUUUUUUUUUUUUUU   " },
        {23,"    UUUUUUUUUUUUUUUUUUUUUU    " }
    });
    bigLetters.Add('V', new Dictionary<int, string>()
    {
        {1, "VVVVVV                  VVVVVV" },
        {2, " VVVVV                  VVVVV " },
        {3, "  VVVVV                VVVVV  " },
        {4, "  VVVVV                VVVVV  " },
        {5, "   VVVVV              VVVVV   " },
        {6, "   VVVVV              VVVVV   " },
        {7, "    VVVVV            VVVVV    " },
        {8, "    VVVVV            VVVVV    " },
        {9, "     VVVVV          VVVVV     " },
        {10,"     VVVVV          VVVVV     " },
        {11,"      VVVVV        VVVVV      " },
        {12,"      VVVVV        VVVVV      " },
        {13,"       VVVVV      VVVVV       " },
        {14,"       VVVVV      VVVVV       " },
        {15,"        VVVVV    VVVVV        " },
        {16,"        VVVVV    VVVVV        " },
        {17,"         VVVVV  VVVVV         " },
        {18,"         VVVVV  VVVVV         " },
        {19,"          VVVVVVVVVV          " },
        {20,"           VVVVVVVV           " },
        {21,"            VVVVVV            " },
        {22,"             VVVV             " },
        {23,"              VV              " }
    });
    bigLetters.Add('W', new Dictionary<int, string>()
    {
        {1, "WWWWWW                  WWWWWW" },
        {2, "WWWWWW                  WWWWWW" },
        {3, "WWWWWW                  WWWWWW" },
        {4, "WWWWWW    WWWWWWWWWW    WWWWWW" },
        {5, "WWWWWW    WWWWWWWWWW    WWWWWW" },
        {6, "WWWWWW    WWWWWWWWWW    WWWWWW" },
        {7, "WWWWWW    WWWWWWWWWW    WWWWWW" },
        {8, "WWWWWW   WWWWW  WWWWW   WWWWWW" },
        {9, "WWWWWW   WWWWW  WWWWW   WWWWWW" },
        {10,"WWWWWW   WWWWW  WWWWW   WWWWWW" },
        {11,"WWWWWW   WWWWW  WWWWW   WWWWWW" },
        {12,"WWWWWW  WWWWW    WWWWW  WWWWWW" },
        {13,"WWWWWW  WWWWW    WWWWW  WWWWWW" },
        {14,"WWWWWW  WWWWW    WWWWW  WWWWWW" },
        {15,"WWWWWW  WWWWW    WWWWW  WWWWWW" },
        {16,"WWWWWW WWWWW      WWWWW WWWWWW" },
        {17,"WWWWWW WWWWW      WWWWW WWWWWW" },
        {18,"WWWWWW WWWWW      WWWWW WWWWWW" },
        {19,"WWWWWW WWWWW      WWWWW WWWWWW" },
        {20,"WWWWWWWWWWW        WWWWWWWWWWW" },
        {21,"WWWWWWWWWWW        WWWWWWWWWWW" },
        {22,"WWWWWWWWWWW        WWWWWWWWWWW" },
        {23,"WWWWWWWWWWW        WWWWWWWWWWW" },
    });
    bigLetters.Add('X', new Dictionary<int, string>()
    {
        {1, "XXXXX                    XXXXX" },
        {2, " XXXXX                  XXXXX " },
        {3, "  XXXXX                XXXXX  " },
        {4, "   XXXXX              XXXXX   " },
        {5, "    XXXXX            XXXXX    " },
        {6, "     XXXXX          XXXXX     " },
        {7, "      XXXXX        XXXXX      " },
        {8, "       XXXXX      XXXXX       " },
        {9, "        XXXXX    XXXXX        " },
        {10,"         XXXXX  XXXXX         " },
        {11,"          XXXXXXXXXX          " },
        {12,"          XXXXXXXXXX          " },
        {13,"          XXXXXXXXXX          " },
        {14,"         XXXXX  XXXXX         " },
        {15,"        XXXXX    XXXXX        " },
        {16,"       XXXXX      XXXXX       " },
        {17,"      XXXXX        XXXXX      " },
        {18,"     XXXXX          XXXXX     " },
        {19,"    XXXXX            XXXXX    " },
        {20,"   XXXXX              XXXXX   " },
        {21,"  XXXXX                XXXXX  " },
        {22," XXXXX                  XXXXX " },
        {23,"XXXXX                    XXXXX" }
    });
    bigLetters.Add('Y', new Dictionary<int, string>()
    {
        {1, "YYYYY                    YYYYY" },
        {2, " YYYYY                  YYYYY " },
        {3, "  YYYYY                YYYYY  " },
        {4, "   YYYYY              YYYYY   " },
        {5, "    YYYYY            YYYYY    " },
        {6, "     YYYYY          YYYYY     " },
        {7, "      YYYYY        YYYYY      " },
        {8, "       YYYYY      YYYYY       " },
        {9, "        YYYYY    YYYYY        " },
        {10,"         YYYYY  YYYYY         " },
        {11,"          YYYYYYYYYY          " },
        {12,"           YYYYYYYY           " },
        {13,"            YYYYYY            " },
        {14,"            YYYYYY            " },
        {15,"            YYYYYY            " },
        {16,"            YYYYYY            " },
        {17,"            YYYYYY            " },
        {18,"            YYYYYY            " },
        {19,"            YYYYYY            " },
        {20,"            YYYYYY            " },
        {21,"            YYYYYY            " },
        {22,"            YYYYYY            " },
        {23,"            YYYYYY            " }
    });
        bigLetters.Add('Z', new Dictionary<int, string>()
    {
        {1, "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" },
        {2, "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" },
        {3, "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" },
        {4, "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" },
        {5, "                          ZZZZ" },
        {6, "                        ZZZZZZ" },
        {7, "                      ZZZZZZ  " },
        {8, "                    ZZZZZZ    " },
        {9, "                  ZZZZZZ      " },
        {10,"                ZZZZZZ        " },
        {11,"              ZZZZZZ          " },
        {12,"            ZZZZZZ            " },
        {13,"          ZZZZZZ              " },
        {14,"        ZZZZZZ                " },
        {15,"      ZZZZZZ                  " },
        {16,"    ZZZZZZ                    " },
        {17,"  ZZZZZZZ                     " },
        {18," ZZZZZZZ                      " },
        {19,"ZZZZZZZ                       " },
        {20,"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" },
        {21,"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" },
        {22,"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" },
        {23,"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" }
    });
    for (int i = 1; i <= 23; i++)
    {    
        foreach (char c in word)
        {
            if (bigLetters.Keys.Contains(c))
            {
                Console.Write($"{bigLetters[c][i]}     ");
            }
        }
        Console.Write("\n");
    }
}
